# Generated by Django 4.2.20 on 2025-05-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_asignatura_nombre'),
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='observacion',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.asignatura'),
        ),
    ]
