# Generated by Django 4.2.20 on 2025-06-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturacurso',
            name='profesor',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_profesor', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje'), ('ciencias', 'Ciencias'), ('historia', 'Historia'), ('ingles', 'Inglés')], max_length=50, unique=True),
        ),
    ]
