# Generated by Django 4.2.21 on 2025-05-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_asignatura_nombre'),
        ('asistencia', '0002_remove_asistencia_observacion_asistencia_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.asignatura'),
        ),
    ]
