# Generated by Django 4.2.20 on 2025-06-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('asistencia', '0002_remove_asignaturacurso_profesor_asignatura_profesor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='profesor',
        ),
        migrations.AddField(
            model_name='asignaturacurso',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_asignadas', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje y Comunicación'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia y Geografía'), ('ingles', 'Inglés')], max_length=50, unique=True),
        ),
    ]
