# Generated by Django 4.2.20 on 2025-06-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
        ('asistencia', '0005_alter_asignaturacurso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturacurso',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas_asignadas', to='usuarios.usuario'),
        ),
    ]
