# Generated by Django 4.2.20 on 2025-06-10 00:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2025)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Año Académico',
                'verbose_name_plural': 'Años Académicos',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='PromedioMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje y Comunicación'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia y Geografía'), ('ingles', 'Inglés')], max_length=20)),
                ('semestre', models.IntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre')])),
                ('ano_academico', models.IntegerField(default=2025)),
                ('promedio', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('total_notas', models.IntegerField(default=0)),
                ('notas_con_porcentaje', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Promedio por Materia',
                'verbose_name_plural': 'Promedios por Materia',
                'ordering': ['ano_academico', 'semestre', 'materia'],
                'unique_together': {('alumno', 'materia', 'semestre', 'ano_academico')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=50)),
                ('semestre', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('numero_nota', models.IntegerField()),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('porcentaje', models.IntegerField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['ano', 'semestre', 'materia', 'numero_nota'],
                'unique_together': {('alumno', 'materia', 'semestre', 'ano', 'numero_nota')},
            },
        ),
    ]
