# Generated by Django 4.2.20 on 2025-06-10 01:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promediomateria',
            options={'ordering': ['ano', 'semestre', 'materia'], 'verbose_name': 'Promedio por Materia', 'verbose_name_plural': 'Promedios por Materia'},
        ),
        migrations.RenameField(
            model_name='promediomateria',
            old_name='fecha_calculo',
            new_name='fecha_actualizacion',
        ),
        migrations.AlterUniqueTogether(
            name='promediomateria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='anoacademico',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='anoacademico',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='anoacademico',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='promediomateria',
            name='ano',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='ano',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='materia',
            field=models.CharField(choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje y Comunicación'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia y Geografía'), ('ingles', 'Inglés')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nota',
            name='numero_nota',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='porcentaje',
            field=models.IntegerField(blank=True, help_text='Porcentaje que representa esta nota en el promedio final', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='semestre',
            field=models.IntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre')]),
        ),
        migrations.AlterField(
            model_name='promediomateria',
            name='materia',
            field=models.CharField(choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje y Comunicación'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia y Geografía'), ('ingles', 'Inglés')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='promediomateria',
            unique_together={('alumno', 'materia', 'semestre', 'ano')},
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['alumno', 'materia', 'semestre', 'ano'], name='notas_nota_alumno__d9dc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['ano', 'semestre'], name='notas_nota_ano_0e9188_idx'),
        ),
        migrations.RemoveField(
            model_name='promediomateria',
            name='ano_academico',
        ),
    ]
