# Generated by Django 4.2.20 on 2025-06-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('notas', '0002_alter_promediomateria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nota',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='nota',
            name='materia',
            field=models.CharField(choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje y Comunicación'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia y Geografía'), ('ingles', 'Inglés')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nota',
            name='numero_nota',
            field=models.IntegerField(choices=[(1, 'Nota 1'), (2, 'Nota 2'), (3, 'Nota 3'), (4, 'Nota 4'), (5, 'Nota 5'), (6, 'Nota 6')]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre')]),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('alumno', 'materia', 'semestre', 'numero_nota', 'ano')},
        ),
    ]
