# Generated by Django 4.2.20 on 2025-06-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_configuracionsistema_alter_nota_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuracionsistema',
            table='notas_configuracion_sistema',
        ),
    ]
