# Generated by Django 4.2.20 on 2025-06-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_alter_configuracionsistema_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionSistema',
        ),
    ]
