# Generated by Django 4.2.20 on 2025-06-15 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_delete_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='ano_academico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='notas.anoacademico'),
        ),
        migrations.AddField(
            model_name='promediomateria',
            name='ano_academico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='notas.anoacademico'),
        ),
        migrations.AlterField(
            model_name='anoacademico',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['ano_academico'], name='notas_nota_ano_aca_3afb57_idx'),
        ),
    ]
