# Generated by Django 4.2.20 on 2025-06-16 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_merge_0006_add_sync_methods_000X_add_sync_methods'),
        ('notas', '0006_nota_ano_academico_promediomateria_ano_academico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='ano_academico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.anoacademico'),
        ),
        migrations.AlterField(
            model_name='promediomateria',
            name='ano_academico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.anoacademico'),
        ),
        migrations.DeleteModel(
            name='AnoAcademico',
        ),
    ]
