# Generated by Django 4.2.20 on 2025-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0008_alter_nota_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='materia',
            field=models.CharField(choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje y Comunicación'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia y Geografía'), ('ingles', 'Inglés'), ('estudios_sociales', 'Estudios Sociales'), ('f_instrumental', 'F. Instrumental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promediomateria',
            name='materia',
            field=models.CharField(choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje y Comunicación'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia y Geografía'), ('ingles', 'Inglés'), ('estudios_sociales', 'Estudios Sociales'), ('f_instrumental', 'F. Instrumental')], max_length=50),
        ),
    ]
