# Generated by Django 4.2.20 on 2025-06-02 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato válido (Ej: 12.345.678-9)', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$')], verbose_name='RUT')),
                ('password', models.CharField(help_text='Contraseña hasheada del usuario', max_length=128, verbose_name='Contraseña')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono debe tener formato válido (Ej: +56 9 1234 5678)', regex='^\\+56\\s9\\s\\d{4}\\s\\d{4}$')], verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador')], max_length=20, verbose_name='Rol')),
                ('estado', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('pending', 'Pendiente')], default='inactive', max_length=20, verbose_name='Estado')),
                ('funcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Función')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
