# Generated by Django 4.2.20 on 2025-05-23 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato válido (Ej: 12345678-9)', regex='^\\d{1,8}-[\\dkK]$')], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono debe tener formato válido (Ej: +56 9 1234 5678)', regex='^\\+56\\s9\\s\\d{4}\\s\\d{4}$')], verbose_name='Teléfono'),
        ),
    ]
