# Generated by Django 4.2.20 on 2025-06-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador'), ('profesor', 'Profesor')], max_length=20, verbose_name='Rol'),
        ),
    ]
