# Generated by Django 4.2.21 on 2025-05-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rut_alter_usuario_telefono'),
    ]

    operations = [
    ]
