# Generated by Django 4.2.20 on 2025-06-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcion',
            field=models.CharField(blank=True, choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje y Comunicación'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia y Geografía'), ('ingles', 'Inglés'), ('estudios_sociales', 'Estudios Sociales'), ('f_instrumental', 'F. Instrumental')], max_length=200, null=True, verbose_name='Asignatura/Función'),
        ),
    ]
