# Generated by Django 4.2.20 on 2025-06-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='funcion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='asignatura',
            field=models.CharField(blank=True, choices=[('matematicas', 'Matemáticas'), ('lenguaje_basica', 'Lenguaje Básica'), ('lenguaje', 'Lenguaje y Comunicación'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia y Geografía'), ('ingles', 'Inglés'), ('estudios_sociales', 'Estudios Sociales'), ('f_instrumental', 'Formación Instrumental')], help_text='Asignatura que imparte el profesor (solo para rol profesor)', max_length=50, null=True, verbose_name='Asignatura'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso'),
        ),
    ]
