# Generated by Django 4.2.21 on 2025-05-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_password_usuario_tipo_identificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_identificacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(help_text='Contraseña hasheada del usuario', max_length=128, verbose_name='Contraseña'),
        ),
    ]
