# Generated by Django 4.2.21 on 2025-05-29 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_tipo_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato válido (Ej: 12.345.678-9)', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$')], verbose_name='RUT'),
        ),
    ]
