# Generated by Django 4.2.20 on 2025-06-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_funcion_usuario_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('profesor', 'Profesor'), ('admin', 'Administrador'), ('superusuario', 'Superusuario')], max_length=20, verbose_name='Rol'),
        ),
    ]
