# Generated by Django 4.2.20 on 2025-06-02 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_institucion', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('parentezco', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
                ('primer_nombre', models.CharField(default='', max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(default='', max_length=50)),
                ('apellido_materno', models.CharField(default='', max_length=50)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion', models.TextField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('nivel', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B')], max_length=2)),
                ('jornada', models.CharField(blank=True, choices=[('diurna', 'Diurna'), ('vespertina', 'Vespertina')], max_length=10, null=True)),
                ('estado_civil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Convive', 'Convive'), ('Unión Civil', 'Unión Civil')], default='Soltero', max_length=15)),
                ('religion', models.CharField(choices=[('Católica', 'Católica'), ('Evangelica', 'Evangelica'), ('Cristiana', 'Cristiana'), ('Musulman', 'Musulman'), ('Judia', 'Judia'), ('Mormona', 'Mormona'), ('Otras', 'Otras'), ('Ninguna', 'Ninguna')], default='Ninguna', max_length=50)),
                ('ultimo_curso_aprobado', models.CharField(blank=True, choices=[('1ro Basico', '1ro Basico'), ('2do Basico', '2do Basico'), ('3ro Basico', '3ro Basico'), ('4to Basico', '4to Basico'), ('5to Basico', '5to Basico'), ('6to Basico', '6to Basico'), ('7mo Basico', '7mo Basico'), ('8vo Basico', '8vo Basico'), ('1ro Medio', '1ro Medio'), ('2do Medio', '2do Medio'), ('3ro Medio', '3ro Medio'), ('4to Medio', '4to Medio')], max_length=20, null=True)),
                ('curso_repetido', models.CharField(choices=[('Ninguno', 'Ninguno'), ('1ro Basico', '1ro Basico'), ('2do Basico', '2do Basico'), ('3ro Basico', '3ro Basico'), ('4to Basico', '4to Basico'), ('5to Basico', '5to Basico'), ('6to Basico', '6to Basico'), ('7mo Basico', '7mo Basico'), ('8vo Basico', '8vo Basico'), ('1ro Medio', '1ro Medio'), ('2do Medio', '2do Medio'), ('3ro Medio', '3ro Medio'), ('4to Medio', '4to Medio')], default='Ninguno', max_length=20)),
                ('anio_repitencia', models.PositiveIntegerField(blank=True, null=True)),
                ('programa_pie', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('profesional_apoyo', models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Psicologo', 'Psicologo'), ('Educador Diferencial', 'Educador Diferencial'), ('Fonoaudiologo', 'Fonoaudiologo'), ('Psicopedagogo', 'Psicopedagogo')], default='Ninguno', max_length=20, null=True)),
                ('informe_psicosocial', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('situacion_laboral', models.CharField(choices=[('Desempleado', 'Desempleado'), ('Dependiente', 'Dependiente'), ('Independiente', 'Independiente'), ('Temporada', 'Temporada')], default='Desempleado', max_length=15)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia_parentezco', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('motivo_retiro', models.TextField(blank=True, null=True)),
                ('apoderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.apoderado')),
            ],
        ),
    ]
