# Generated by Django 4.2.20 on 2025-04-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.IntegerField()),
                ('nivel', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3')])),
                ('jornada', models.CharField(choices=[('diurna', 'Diurna'), ('vespertina', 'Vespertina')], max_length=10)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('parentezco_contacto_emergencia', models.CharField(max_length=50)),
                ('telefono_contacto_emergencia', models.CharField(max_length=20)),
                ('apoderado', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
            ],
        ),
    ]
