# Generated by Django 4.2.20 on 2025-04-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_creacion',
            field=models.DateTimeField(default='2025-04-25 00:00:00'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
