# Generated by Django 4.2.20 on 2025-06-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Año Académico',
                'verbose_name_plural': 'Años Académicos',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='EstadoAlumnoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nivel_ano', models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B')], max_length=2, null=True)),
                ('jornada_ano', models.CharField(blank=True, choices=[('diurna', 'Diurna'), ('vespertina', 'Vespertina')], max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_anuales', to='alumnos.alumno')),
                ('ano_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.anoacademico')),
            ],
            options={
                'verbose_name': 'Estado Anual del Alumno',
                'verbose_name_plural': 'Estados Anuales de Alumnos',
                'unique_together': {('alumno', 'ano_academico')},
            },
        ),
    ]
