# Generated by Django 4.2.20 on 2025-06-11 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_anoacademico_estadoalumnoanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B')], max_length=2)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_anos', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Matrícula por Año',
                'verbose_name_plural': 'Matrículas por Año',
            },
        ),
        migrations.AlterField(
            model_name='anoacademico',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anoacademico',
            name='ano',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2025)]),
        ),
        migrations.DeleteModel(
            name='EstadoAlumnoAnual',
        ),
        migrations.AddField(
            model_name='matriculaano',
            name='ano_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='alumnos.anoacademico'),
        ),
        migrations.AlterUniqueTogether(
            name='matriculaano',
            unique_together={('alumno', 'ano_academico')},
        ),
    ]
