# Generated by Django 4.2.20 on 2025-04-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_activo_alumno_correo_electronico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apoderado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='parentezco_contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='telefono_contacto_emergencia',
        ),
    ]
