# Generated by Django 4.2.20 on 2025-06-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_matriculaano_alter_anoacademico_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoacademico',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='jornada',
            field=models.CharField(blank=True, choices=[('diurna', 'Diurna'), ('vespertina', 'Vespertina')], help_text='Jornada por defecto (se puede sobrescribir por año)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nivel',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B')], help_text='Nivel por defecto (se puede sobrescribir por año)', max_length=2),
        ),
        migrations.CreateModel(
            name='AlumnoAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B')], max_length=2)),
                ('jornada', models.CharField(blank=True, choices=[('diurna', 'Diurna'), ('vespertina', 'Vespertina')], max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anos_academicos', to='alumnos.alumno')),
                ('ano_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='alumnos.anoacademico')),
            ],
            options={
                'verbose_name': 'Alumno por Año',
                'verbose_name_plural': 'Alumnos por Año',
                'ordering': ['-ano_academico__ano', 'alumno__apellido_paterno', 'alumno__primer_nombre'],
                'unique_together': {('alumno', 'ano_academico')},
            },
        ),
    ]
