# Generated by Django 5.2 on 2025-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_remove_alumno_apoderado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
