# Generated by Django 5.2 on 2025-04-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_alumno_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='edad',
        ),
    ]
