# Generated by Django 4.2.20 on 2025-06-11 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_anoacademico_fecha_modificacion_alter_alumno_jornada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnoano',
            options={'verbose_name': 'Alumno por Año', 'verbose_name_plural': 'Alumnos por Año'},
        ),
        migrations.RemoveField(
            model_name='alumnoano',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='alumnoano',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='anoacademico',
            name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='jornada',
            field=models.CharField(blank=True, choices=[('diurna', 'Diurna'), ('vespertina', 'Vespertina')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nivel',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B')], max_length=2),
        ),
        migrations.AlterField(
            model_name='alumnoano',
            name='fecha_matricula',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='alumnoano',
            name='jornada',
            field=models.CharField(choices=[('diurna', 'Diurna'), ('vespertina', 'Vespertina')], default=2025, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MatriculaAno',
        ),
    ]
