# Generated by Django 4.2.20 on 2025-06-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_alumnoano_options_and_more'),
    ]

    operations = [
    ]
