# Generated by Django 5.2 on 2025-04-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_remove_alumno_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
