# Generated by Django 4.2.20 on 2025-06-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_add_sync_methods'),
        ('alumnos', '000X_add_sync_methods'),
    ]

    operations = [
    ]
