# Generated by Django 4.2.20 on 2025-06-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_merge_0006_add_sync_methods_000X_add_sync_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='diagnostico',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('OK', 'OK')], default='No', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales del alumno', null=True),
        ),
    ]
