# Generated by Django 5.2 on 2025-04-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_remove_alumno_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nivel',
            field=models.CharField(max_length=2),
        ),
    ]
