# Generated by Django 5.2 on 2025-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alter_alumno_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='jornada',
            field=models.CharField(blank=True, choices=[('diurna', 'Diurna'), ('vespertina', 'Vespertina')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nivel',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('2A', '2A'), ('3B', '3B')], max_length=2),
        ),
    ]
