# Generated by Django 4.2.20 on 2025-05-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_apoderado_alter_alumno_direccion_alumno_apoderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
        migrations.AddField(
            model_name='alumno',
            name='anio_repitencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_materno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia_parentezco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso_repetido',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('1ro Basico', '1ro Basico'), ('2do Basico', '2do Basico'), ('3ro Basico', '3ro Basico'), ('4to Basico', '4to Basico'), ('5to Basico', '5to Basico'), ('6to Basico', '6to Basico'), ('7mo Basico', '7mo Basico'), ('8vo Basico', '8vo Basico'), ('1ro Medio', '1ro Medio'), ('2do Medio', '2do Medio'), ('3ro Medio', '3ro Medio'), ('4to Medio', '4to Medio')], default='Ninguno', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Convive', 'Convive'), ('Unión Civil', 'Unión Civil')], default='Soltero', max_length=15),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='informe_psicosocial',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='alumno',
            name='motivo_retiro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='primer_nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='profesional_apoyo',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Psicologo', 'Psicologo'), ('Educador Diferencial', 'Educador Diferencial'), ('Fonoaudiologo', 'Fonoaudiologo'), ('Psicopedagogo', 'Psicopedagogo')], default='Ninguno', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='programa_pie',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='alumno',
            name='rut',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='situacion_laboral',
            field=models.CharField(choices=[('Desempleado', 'Desempleado'), ('Dependiente', 'Dependiente'), ('Independiente', 'Independiente'), ('Temporada', 'Temporada')], default='Desempleado', max_length=15),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ultimo_curso_aprobado',
            field=models.CharField(blank=True, choices=[('1ro Basico', '1ro Basico'), ('2do Basico', '2do Basico'), ('3ro Basico', '3ro Basico'), ('4to Basico', '4to Basico'), ('5to Basico', '5to Basico'), ('6to Basico', '6to Basico'), ('7mo Basico', '7mo Basico'), ('8vo Basico', '8vo Basico'), ('1ro Medio', '1ro Medio'), ('2do Medio', '2do Medio'), ('3ro Medio', '3ro Medio'), ('4to Medio', '4to Medio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='religion',
            field=models.CharField(choices=[('Católica', 'Católica'), ('Evangelica', 'Evangelica'), ('Cristiana', 'Cristiana'), ('Musulman', 'Musulman'), ('Judia', 'Judia'), ('Mormona', 'Mormona'), ('Otras', 'Otras'), ('Ninguna', 'Ninguna')], default='Ninguna', max_length=50),
        ),
    ]
