# Generated by Django 4.2.20 on 2025-05-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0013_remove_alumno_fecha_creacion_remove_alumno_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
