# Generated by Django 4.2.20 on 2025-05-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0014_alter_alumno_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3')])),
                ('letra', models.CharField(choices=[('a', 'Diurna (A)'), ('b', 'Vespertina (B)')], max_length=1)),
                ('asignatura', models.CharField(blank=True, choices=[('matematicas', 'Matemáticas'), ('lenguaje', 'Lenguaje y Comunicación'), ('ciencias', 'Ciencias Naturales'), ('historia', 'Historia y Geografía'), ('ingles', 'Inglés'), ('educacion_fisica', 'Educación Física'), ('artes', 'Artes Visuales'), ('musica', 'Música'), ('tecnologia', 'Tecnología'), ('religion', 'Religión'), ('orientacion', 'Orientación'), ('otro', 'Otra Asignatura')], max_length=100, null=True)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='cursos', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'unique_together': {('nivel', 'letra', 'asignatura')},
            },
        ),
    ]
