# Generated by Django 4.2.20 on 2025-06-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
    ]
