# Generated by Django 4.2.20 on 2025-05-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_unique_together_remove_curso_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignatura',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='cursos.curso'),
        ),
    ]
