# Generated by Django 4.2.20 on 2025-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20250610_1233'),
        ('cursos', '0002_remove_alumnos_field'),
    ]

    operations = [
    ]
