# Generated by Django 4.2.20 on 2025-06-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('cursos', '0003_merge_20250610_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='alumnos.alumno'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nivel', 'letra')},
        ),
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('anio', models.PositiveIntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Matrícula en Curso',
                'verbose_name_plural': 'Matrículas en Cursos',
                'unique_together': {('alumno', 'curso', 'anio')},
            },
        ),
    ]
