# Generated by Django 4.2.20 on 2025-05-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_asignatura_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(default='Sin Asignatura', max_length=100),
        ),
    ]
