# Generated by Django 4.2.20 on 2025-06-02 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_alter_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('inicio', 'Inicio'), ('estudiantes', 'Estudiantes'), ('cursos', 'Cursos'), ('notas', 'Notas'), ('asistencia', 'Asistencia'), ('usuarios', 'Usuarios'), ('permisos', 'Permisos')], max_length=50)),
                ('puede_ver', models.BooleanField(default=False)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_asignados', to='usuarios.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuarios',
                'ordering': ['usuario__nombres', 'modulo'],
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
